base: "core24"
confinement: "devmode" # use 'strict' once you have the right plugs and slots
description: "Yet another remote desktop solution, written in Rust. Works out of the box with no configuration required"
grade: "stable"
name: "rustdesk"
summary: "An open-source remote desktop application designed for self-hosting"
parts:
  rustdesk:
    override-build: |
      git clone https://github.com/microsoft/vcpkg
      cd vcpkg
      git checkout 2023.04.15
      cd ..
      vcpkg/bootstrap-vcpkg.sh
      export VCPKG_ROOT=$HOME/vcpkg
      vcpkg/vcpkg install libvpx libyuv opus aom

      craftctl default
    plugin: "dump"
    source: "."
version: "1.4.1"
