base: "core24"
confinement: "devmode" # use 'strict' once you have the right plugs and slots
description: "Yet another remote desktop solution, written in Rust. Works out of the box with no configuration required"
grade: "stable"
name: "rustdesk"
summary: "An open-source remote desktop application designed for self-hosting"
parts:
  rustdesk:
    plugin: "dump"
    source: "./rustdesk.deb"
    source-type: "deb"
version: "1.4.1"
